learndbt:
  outputs:
    dev:
      account: enb39479.us-east-1
      database: analytics
      password: '12345678'
      role: transform_role
      schema: dbt
      threads: 1
      type: snowflake
      user: transform_user
      warehouse: transform_wh
  target: dev
